export default [
  {
    id: "",
    categoryId: "adayinyourlife",
    author: "Yumna Al-Arashi",
    start: "",
    title: "",
    image: "tmp_1.png",
  },
  {
    id: "",
    categoryId: "whatareyou",
    author: "Jeremy Lee-Stone",
    start: "",
    title: "",
    image: "tmp_1.png",
  },
  // {
  //   id: '',
  //   categoryId: 'signus',
  //   author: "Haatepah Clearbear",
  //   start: '',
  //   title: '',
  //   image: 'tmp_1.png'
  // },
  {
    id: "",
    categoryId: "lectureus",
    author: "Kymon Palau",
    start: "",
    title: "",
    image: "tmp_1.png",
  },
  {
    id: "",
    categoryId: "danceyour",
    author: "Aïcha",
    start: "",
    title: "",
    image: "tmp_1.png",
  },
  {
    id: "",
    categoryId: "howdoesitfeel",
    author: "Felukah",
    start: "",
    title: "",
    image: "tmp_1.png",
  },
  {
    id: "",
    categoryId: "showus",
    author: "Original Rose",
    start: "",
    title: "",
    image: "tmp_1.png",
  },
  {
    id: "",
    categoryId: "takeinventory",
    author: "Jasmine Solano",
    start: "",
    title: "",
    image: "tmp_1.png",
  },
  {
    id: "",
    categoryId: "teachus",
    author: "Mimi Zhu",
    start: "",
    title: "",
    image: "tmp_1.png",
  },
  {
    id: "",
    categoryId: "lectureme",
    author: "Mandy Harris Williams",
    start: "",
    title: "",
    image: "tmp_1.png",
  },
  {
    id: "",
    categoryId: "showus",
    author: "Ssegawa-Ssekintu Kiwanuka",
    start: "",
    title: "",
    image: "tmp_1.png",
  },
]
